name: 'Add Labels'
on:
  pull_request:
    types: opened
jobs:
  add-labels:
    name: Add Labels to PR
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v5
        with:
          configuration-path: .github/changelog/labels.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
