name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run format:check
      - run: npm run lint

  test-latest:
    name: test latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Plugin
        uses: ./
        with:
          npm-mode: true

      - run: sf --version
        continue-on-error: true

      - run: /home/runner/actions_sf_cli/bin/sf --version
        continue-on-error: true

  # test-specific-version:
  #   name: test specific version
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       id: checkout
  #       uses: actions/checkout@v4

  #     - name: Run Plugin
  #       uses: ./
  #       with:
  #         sf-cli-version: 2.33.3

  #     - run: sf --version
