name: 'Publish GitHub Action'
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tgymnich/publish-github-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # - run: echo "VERSION=npm version minor --no-git-tag-version" >> $GITHUB_ENV
      # - uses: fregante/setup-git-user@v2
      # - run: git push origin HEAD:${{ github.ref_name }}
