name: 'Publish GitHub Action'
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'dist/**'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tgymnich/publish-github-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  bump-version:
    runs-on: ubuntu-latest
    needs: publish
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: fregante/setup-git-user@v2
      - run: npm version patch --no-git-tag-version
      - run: git add package.json package-lock.json
      - run: echo "VERSION=$(npm pkg get version | tr -d '\"')" >> $GITHUB_ENV
      - run: git commit -m 'Bump version to ${{ env.VERSION }}'
      - run: echo '::notice::Incrementing version to ${{ env.VERSION }}'
      - run: git push origin HEAD:${{ github.ref_name }}
